spring: 
  profiles:
    active:
    - dev
---
server:
  port: 8001

  #mybatis配置
mybatis:
  type-aliases-package: com.daji.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tab_emp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #修改Eureka上的默认描述信息！

#info配置
info:
  app.name: chenyuhua-springcloud
  company.name: blog.chenyuhua.com
---
server:
  port: 8001

  #mybatis配置
mybatis:
  type-aliases-package: com.daji.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#spring配置
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tab_emp1?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #修改Eureka上的默认描述信息！

#info配置
info:
  app.name: chenyuhua-springcloud
  company.name: blog.chenyuhua.com
